language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "ArduinoUnit"
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: Deploy Documentation
      script: 
        - source <(curl -SLs https://raw.githubusercontent.com/bakercp/ci/master/deploy_documentation.sh)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: false
        local_dir: docs/html
        on:
          branch: master
